name: Log batch sensor data

on:
  schedule:
    - cron: "*/5 * * * *"  # setiap 5 menit
  workflow_dispatch:

jobs:
  log_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch batch data from Cloudflare
        run: |
          curl -s https://your-cloudflare-url.workers.dev/api/batch -o data.json
          if [ ! -s data.json ]; then
            echo "No new data, exiting..."
            exit 0
          fi

      - name: Convert to CSV
        run: |
          echo "timestamp,value" > logs/tmp.csv
          jq -r '.[] | [.ts, .value] | @csv' data.json >> logs/tmp.csv

      - name: Rename CSV with timestamp
        run: |
          dt=$(date +'%Y-%m-%dT%H-%M-%S')
          mv logs/tmp.csv logs/$dt.csv

      - name: Delete logs older than 30 days
        run: |
          find logs -name "*.csv" -type f -mtime +30 -exec git rm {} \;

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add logs/*.csv
          git commit -m "Log data at $(date)"
          git push
